site_name: Hopcolony
site_description: Focus on you app. Let us manage your backend.
site_url: https://www.hopcolony.io/latest/docs/
theme:
  name: material
  custom_dir: overrides
  palette:
  - scheme: default
    primary: blue
    accent: amber
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
  - scheme: slate
    primary: blue
    accent: amber
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  # logo: img/icon-white.svg
  # favicon: img/favicon.png
  language: en
repo_name: hopcolony/hopcolony
repo_url: https://github.com/hopcolony/hopcolony
plugins:
- search
nav:
# - Introduction: index.md
- index.md
- initialize.md
- documents.md
- cli.md
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed
extra:
  alternate:
  - link: /latest/docs/
    name: en - English
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- js/termynal.js
- js/custom.js
