name: Build English Version
on:
  push:
    branches:
      - master

jobs:
  setup-build-push:
    name: Setup, Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: docker/build-push-action@v2
      with:
        push: true
        context: docs
        file: Dockerfile
        tags: hopcolony/docs:en
        build-args: lang=en